### ISSUE TITLE
compilation error with laravel mix

### ISSUE THREAD

**Issue by fannyfan414** [seleb/chunk-progress-webpack-plugin#1]
webpack.mix.js:
`const ChunkProgressWebpackPlugin = require('chunk-progress-webpack-plugin');
mix.webpackConfig({
    plugins: [
        new BundleAnalyzerPlugin(),               
    ],
    output: {
        // chunkFilename: path.join('js', '[name].[hash].js'),
        publicPath: '/',
        chunkFilename: "js/[name].[hash].js"
    }
});`
get error:

> Cannot read property 'compilation' of undefined
>     at ChunkProgressWebpackPlugin.apply (...\node_modules\chunk-progress-webpack-plugin\index.js:3:18)

**Comment by seleb** [comment]
Could you provide a more complete repro case (i.e. a `package.json` and entry point)? I tried to setup a test for this and had no issues compiling.

**Comment by fannyfan414** [comment]
Hey, thanks for answer. My webpack.mix.js https://pastebin.com/6dPM888U
My package.json: https://pastebin.com/263tJ4pm
Run command 
> npm run watch

>  @ watch G:\OSPanel\domains\s
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel
> -mix/setup/webpack.config.js
> 
> G:\OSPanel\domains\s\node_modules\webpack\bin\webpack.js:348
>                         throw err;
>                         ^
> 
> TypeError: Cannot read property 'compilation' of undefined
>     at ChunkProgressWebpackPlugin.apply (G:\OSPanel\domains\s\node_modules\chunk-progress-webpack-plugin\index.js:3:18)
>     at Compiler.apply (G:\OSPanel\domains\s\node_modules\tapable\lib\Tapable.js:375:16)
>     at webpack (G:\OSPanel\domains\s\node_modules\webpack\lib\webpack.js:33:19)
>     at processOptions (G:\OSPanel\domains\s\node_modules\webpack\bin\webpack.js:335:15)
>     at yargs.parse (G:\OSPanel\domains\s\node_modules\webpack\bin\webpack.js:397:2)
>     at Object.Yargs.self.parse (G:\OSPanel\domains\s\node_modules\yargs\yargs.js:533:18)
>     at Object.<anonymous> (G:\OSPanel\domains\s\node_modules\webpack\bin\webpack.js:152:7)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by seleb** [comment]
That `package.json` is missing a dependency on `webpack`, and when I simply installed latest and ran (with the chunk progress plugin commented out) it failed to compile with the following error:
```
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (D:\Work\webpack test\node_modules\webpack\lib\Chunk.js:824:9)
    at D:\Work\webpack test\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at D:\Work\webpack test\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work\webpack test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work\webpack test\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (D:\Work\webpack test\node_modules\webpack\lib\Compilation.js:1214:27)
    at hooks.make.callAsync.err (D:\Work\webpack test\node_modules\webpack\lib\Compiler.js:547:17)
    at _err0 (eval at create (D:\Work\webpack test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (D:\Work\webpack test\node_modules\webpack\lib\Compilation.js:1065:12)
    at processModuleDependencies.err (D:\Work\webpack test\node_modules\webpack\lib\Compilation.js:981:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by seleb** [comment]
Closing due to lack of info; feel free to re-open if the issue persists.
