### ISSUE TITLE
Handling compressed content download

### ISSUE THREAD

**Issue by Xesenix** [seleb/chunk-progress-webpack-plugin#2]
When downloading gziped content when XHR progress events set `event.lengthComputable` to `false` value for `event.total` is set to `0` check:
[XMLHttpRequest onprogress total is always 0 on Chrome](https://stackoverflow.com/questions/27767954/xmlhttprequest-onprogress-total-is-always-0-on-chrome) 
and 
[How can I use deflated/gzipped content with an XHR onProgress function?](https://stackoverflow.com/questions/15097712/how-can-i-use-deflated-gzipped-content-with-an-xhr-onprogress-function/32799706#32799706)

As solution to this problem is adding additional header info about full size of downloaded modules we would need possibility to read content size from different header value that `content-size`. As developers may use different headers each time some configuration function would be nice to have not sure how to add such function to webpack plugin but inside promises it may looks something like this:

```js
// header request promise
.then((event) => {
  const total = getFileTotalSize(event);
  progress.totalSize += total;
  ...
})
// and then in progress event handler
document.dispatchEvent(new CustomEvent(
  'chunk-progress-webpack-plugin',
  {
    detail: {
      loaded,
      total: progress.totalSize,
      resource: {
        url,
	loaded: event.loaded, // this actually refers to decompressed size
	total: event.lengthComputable ? event.total : total, // total is defined above as result of getFileTotalSize
      }
    }
}));
```
and with default implementation set to
```js
function getFileTotalSize(event) {
  return parseInt(event.target.getResponseHeader('content-length'), 10);
}
```
then in webpack plugin config developer could do something like:
```js
new ChunkProgressWebpackPlugin({
  getFileTotalSize: (event) => {
    return parseInt(event.target.getResponseHeader('x-decompressed-content-length') || event.target.getResponseHeader('content-length'), 10);
  }
}),
```

If I find some time to research how to add configuration to webpack plugin I can make PR with fix.

**Comment by seleb** [comment]
Hmm that's an interesting issue, I didn't realize compressed resources didn't report their size.

Given that it seems the solution will always require something custom, would it be simpler to include `originalEvent: event` in the custom event detail, rather than introducing configuration to the plugin? I believe that would provide the flexibility needed without complicating things for the more common simple use case.

**Comment by Xesenix** [comment]
That also is a possibility but it would require parsing that base even for each subsequential call not sure if that's worth it but could be more future proof. That is if there won't be some strange issues with garbage collecting events.

**Comment by seleb** [comment]
perf should be negligible for something like that, and it's something that could easily be cached on the caller's end if needed (e.g. using `resource.url` as a key). garbage collection should be fine too; in the worst case it may only exacerbate an existing memory leak, not introduce a new one

**Comment by Xesenix** [comment]
Sorry for late review  busy week https://github.com/seleb/chunk-progress-webpack-plugin/pull/3#pullrequestreview-267519868

**Comment by seleb** [comment]
see #4; lmk if that provides what's needed

**Comment by Xesenix** [comment]
Thx looks that it works a little bit inconvenient overriding for resource progress but in end its possible to get correct size from originalEvent target.

In case someone ever looks for how to do it here is an example, let say your server adds additional header to compressed modules called `x-decompressed-content-length`:
on server if you use express you can do something like this:
```js
const expressStaticGzip = require('express-static-gzip');
const decompressedStats = {};
server.use(expressStaticGzip(`path/to/build`, {
  setHeaders(res, path, stat) {
    // add file full size header
    const decopressedPath = path.replace(/\.gz$/, '');
    if (!decompressedStats[decopressedPath]) {
      decompressedStats[decopressedPath] = fs.statSync(path.replace(/\.gz$/, ''));
    }
    res.set('x-decompressed-content-length', decompressedStats[decopressedPath].size);
  },
}));
```
in application code you can define something like this
```js
export function preload(renderProgress, document) {
  let animationFrameHandler;
  const progress = {}; // key resource url value { url: string, loaded: number, total: number }
  function preloadProgress(event = {}) {
    const { detail = {} } = event;
    const { originalEvent = {}, resource = {} } = detail;
    const { target = null, lengthComputable = false } = originalEvent;
    // this is this little bit inconvinient part but not masive problem
    const total = target
      ? lengthComputable
        ? parseInt(target.getResponseHeader('content-length'), 10)
        : parseInt(target.getResponseHeader('x-decompressed-content-length'), 10)
      : 0;
    // add total size to progress object
    if (resource.url) {
      progress[resource.url] = Object.assign(progress[resource.url] || {}, resource, { total });
    }
    // then you can use progress object for rendering progress
    animationFrameHandler = requestAnimationFrame(() => {
      if (animationFrameHandler) {
        renderProgress(progress);
      }
    });
  }
  document.addEventListener('chunk-progress-webpack-plugin', preloadProgress);
  // return cleanup callback
  return () => {
    document.removeEventListener('chunk-progress-webpack-plugin', preloadProgress);
    cancelAnimationFrame(animationFrameHandler);
    animationFrameHandler = null;
  };
}
```
and simplest example use case would be:
```js
preload(console.log, document);
```
